version: '2'
services:
  tttserver:
    image: olethoeb/ttt_server
    restart: always
    networks:
      - frontproxy_default
      - default
    environment:
      - VIRTUAL_HOST=ttt.olethoeb.me
networks:
  frontproxy_default:
    external: true